### PR TITLE
HC-353 improved dependency and requirement capturing for notebook PGEs

### PR DESCRIPTION
**Pull request by DustinKLo**
related ticket: https://hysds-core.atlassian.net/browse/HC-353

added `requirements.ipynb` to project on create
edited `Dockerfile` to execute `requirements.ipynb` on build

### CODE REVIEW

**Comment by DustinKLo** [comment]
@pymonger @jimmie can you test this on your cluster just in case?
the `container-builder` job was able to build the docker image but errored out b/c elasticsearch is broken on my mozart instance

**Comment by pymonger** [comment]
@DustinKLo: I get this error:
```
Traceback (most recent call last):
  File "/home/jovyan/myenv/bin/notebook-pge-wrapper", line 33, in <module>
    sys.exit(load_entry_point('notebook-pge-wrapper==1.0.3', 'console_scripts', 'notebook-pge-wrapper')())
  File "/home/jovyan/myenv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/myenv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/myenv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/myenv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/myenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/myenv/lib/python3.8/site-packages/notebook_pge_wrapper-1.0.3-py3.8.egg/notebook_pge_wrapper/cli.py", line 125, in create
    docker_template = read_docker_template(os.path.join(templates, __DOCKERFILE_TEMPLATE))
  File "/home/jovyan/myenv/lib/python3.8/site-packages/notebook_pge_wrapper-1.0.3-py3.8.egg/notebook_pge_wrapper/cli.py", line 68, in read_docker_template
    with open(f, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/myenv/lib/python3.8/site-packages/notebook_pge_wrapper-1.0.3-py3.8.egg/notebook_pge_wrapper/../templates/Dockerfile.template'
```
Tried installing it using `pip install -e .`, `pip install .`, and `python setup.py install` and they all end up with that error.

**Comment by DustinKLo** [comment]
@pymonger  how are you testing it?
i'm unable to run `virtualenv` in my jupyter cluster
```bash
$ virtualenv env_test
# sh: virtualenv: command not found
```

**Comment by pymonger** [comment]
> @pymonger how are you testing it?
> i'm unable to run `virtualenv` in my jupyter cluster
> 
> ```shell
> $ virtualenv env_test
> # sh: virtualenv: command not found
> ```

I run `sudo conda install virtualenv`.

My bad. Let me retry it again without the use of virtualenv.

**Review by pymonger — APPROVED** [review]
LGTM. My test on nisar-jupyter worked well end-to-end.

**Pull request merged**
